CREATE TABLE [dbo].[Artist]
(
	[Id_ARTIST] INT NOT NULL IDENTITY,
	[NAME] NVARCHAR(50) NOT NULL,
	[BIRTH_DATE] DATE NOT NULL,
	[DEATH_DATE] DATE NULL
	CONSTRAINT PK_ARTIST PRIMARY KEY ([ID_ARTIST]),
	CONSTRAINT UK_ARTIST__NAME UNIQUE ([NAME]),
	CONSTRAINT CK_ARTIST__DEATH CHECK ([DEATH_DATE] > [BIRTH_DATE])
)
