CREATE TABLE [dbo].[Track]
(
	[Id_TRACK] INT NOT NULL IDENTITY,
	[NAME] NVARCHAR(50) NOT NULL,
	[DURATION] INT NOT NULL,
	[GENRE_ID] INT NOT NULL
	CONSTRAINT PK_TRACK PRIMARY KEY ([ID_TRACK]),
	CONSTRAINT FK_TRACK_GENRE FOREIGN KEY ([GENRE_ID])
		REFERENCES GENRE([ID_GENRE]),
	CONSTRAINT UK_TRACK__NAME UNIQUE ([NAME]),
	CONSTRAINT CK_TRACK_DURATION CHECK ([DURATION] > 0)
)
